### ISSUE TITLE
[BUG] Error on server startup

### ISSUE THREAD

**Issue by TeQTabanca** [Tanguygab/TAB-Additions#21]
Mc Version: 1.12.2-Spigot
Plugin Version: 1.6.7

```
[11:49:14 INFO]: [TAB-Additions] Enabling TAB-Additions v1.6.7
[11:49:14 WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.ClientboundCustomChatCompletionsPacket
[11:49:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
[11:49:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[11:49:14 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[11:49:14 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[11:49:14 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[11:49:14 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[11:49:14 WARN]:        at io.github.tanguygab.tabadditions.spigot.SpigotPlatform.<init>(SpigotPlatform.java:44)
[11:49:14 WARN]:        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:18)
[11:49:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:49:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[11:49:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[11:49:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[11:49:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[11:49:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[11:49:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[11:49:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[11:49:14 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[11:49:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[11:49:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Tanguygab** [comment]
right, forgot about that

**Comment by Tanguygab** [comment]
fixed https://github.com/Tanguygab/TAB-Additions/releases/download/1.6.7/TAB-Additions-1.6.7.jar
