### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by DoctaEnkoda** [Tanguygab/TAB-Additions#3]
`java.lang.NoSuchMethodError: 'void me.neznamy.tab.shared.config.YamlConfigurationFile.<init>(java.io.InputStream, java.io.File)'
        at io.github.tanguygab.tabadditions.shared.SharedTA.reload(SharedTA.java:45) ~[?:?]
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.reload(TABAdditionsSpigot.java:40) ~[?:?]
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:30) ~[?:?]`

**Comment by Tanguygab** [comment]
Yeah that's because you need pre-releases, you'll need to wait for the next TAB version to come out
