### ISSUE TITLE
The TAB-Additions plugin does not work in the current build version of TAB.

### ISSUE THREAD

**Issue by TeQTabanca** [Tanguygab/TAB-Additions#32]
### Error:
```
[11:27:57 INFO]: [TAB-Additions] Enabling TAB-Additions v2.0.0-SNAPSHOT
[11:27:58 ERROR]: Error occurred while enabling TAB-Additions v2.0.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'me.neznamy.tab.api.ProtocolVersion me.neznamy.tab.shared.TAB.getServerVersion()'
        at io.github.tanguygab.tabadditions.spigot.SpigotPlatform.<init>(SpigotPlatform.java:43) ~[TAB-Additions-2.0.0-SNAPSHOT.jar:?]
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:10) ~[TAB-Additions-2.0.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### TAB Version: 4.0.0-SNAPSHOT (Build #752)

**Comment by TeQTabanca** [comment]
...?

**Comment by Tanguygab** [comment]
somehow I missed that, I'll send you a jar in a few minutes

**Comment by Tanguygab** [comment]
[TAB-Additions-2.0.0-SNAPSHOT.zip](https://github.com/Tanguygab/TAB-Additions/files/11657494/TAB-Additions-2.0.0-SNAPSHOT.zip)
this took longer than I had hoped it would
