### ISSUE TITLE
[Bug Report] Purpur-1.20.4

### ISSUE THREAD

**Issue by ViniciusManoelCarvalho** [Tanguygab/TAB-Additions#40]
[16:36:43 ERROR]: Error occurred while enabling TAB-Additions v2.0.7 (Is it up to date?)
java.lang.AbstractMethodError: Method io/github/tanguygab/tabadditions/shared/features/chat/Chat.getCommand()Ljava/lang/String; is abstract
        at io.github.tanguygab.tabadditions.shared.features.chat.Chat.getCommand(Chat.java) ~[TAB-Additions-2.0.7.jar:?]
        at me.neznamy.tab.shared.FeatureManager.registerFeature(FeatureManager.java:397) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.registerFeature(TABAdditions.java:96) ~[TAB-Additions-2.0.7.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.loadFeatures(TABAdditions.java:102) ~[TAB-Additions-2.0.7.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.reload(TABAdditions.java:79) ~[TAB-Additions-2.0.7.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.load(TABAdditions.java:56) ~[TAB-Additions-2.0.7.jar:?]
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:11) ~[TAB-Additions-2.0.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-463]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:421) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:374) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.reload(PaperPluginUtil.java:526) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-463]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:984) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-463]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:36:43 INFO]: [TAB-Additions] Disabling TAB-Additions v2.0.7

TAB-Additions-2.0.7
TAB-4.1.3-SNAPSHOT

**Comment by ViniciusManoelCarvalho** [comment]
And the same with TAB-Additions 2.0.8

[16:41:21 ERROR]: Error occurred while enabling TAB-Additions v2.0.8 (Is it up to date?)
java.lang.AbstractMethodError: Receiver class io.github.tanguygab.tabadditions.shared.features.chat.Chat does not define or inherit an implementation of the resolved method 'abstract java.lang.String getCommand()' of interface me.neznamy.tab.shared.features.types.CommandListener.
        at me.neznamy.tab.shared.FeatureManager.registerFeature(FeatureManager.java:397) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.registerFeature(TABAdditions.java:96) ~[TAB-Additions-2.0.8.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.loadFeatures(TABAdditions.java:102) ~[TAB-Additions-2.0.8.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.reload(TABAdditions.java:79) ~[TAB-Additions-2.0.8.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.load(TABAdditions.java:56) ~[TAB-Additions-2.0.8.jar:?]
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:11) ~[TAB-Additions-2.0.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-463]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-463]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-463]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-463]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-463]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Tanguygab** [comment]
did you update TAB ?

**Comment by SamGamerYT** [comment]
Any news?

**Comment by Tanguygab** [comment]
completely forgot about this 😅 let me  check

**Comment by Tanguygab** [comment]
https://github.com/Tanguygab/TAB-Additions/releases/tag/2.0.9
