### ISSUE TITLE
Whenever a player enters the server, all the nametags disappear

### ISSUE THREAD

**Issue by cosmunn** [Tanguygab/TAB-Additions#43]
Purpur-2176 1.20.4
TAB version 4.1.4
TAB-Additions version 2.0.11

Stack trace:
```
[TAB v4.1.4] An error was thrown when executing task
java.lang.IllegalStateException: This player is not loaded yet. Try again later
	at TAB v4.1.4.jar//me.neznamy.tab.shared.platform.TabPlayer.ensureLoaded(TabPlayer.java:291)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.features.nametags.NameTag.showNameTag(NameTag.java:289)
	at TAB-Additions-2.0.11.jar//io.github.tanguygab.tabadditions.shared.features.ConditionalNametags.refresh(ConditionalNametags.java:54)
	at TAB-Additions-2.0.11.jar//io.github.tanguygab.tabadditions.shared.features.ConditionalNametags.refresh(ConditionalNametags.java:45)
	at TAB-Additions-2.0.11.jar//io.github.tanguygab.tabadditions.shared.features.ConditionalNametags.onJoin(ConditionalNametags.java:32)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:147)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:27)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:158)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$1(CpuManager.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Every time a player enters the server all the nametags disappear, and the plugin throws an error, saying "This player is not loaded yet. Try again later". The stack trace is included above.
Reloading TAB fixes it, but that's a workaround. It only happens with TAB-Additions installed so I am reporting it here, but I am unsure if I should also report it to TAB's issue tracker as well.

**Comment by Tanguygab** [comment]
Try this 
[TAB-Additions-2.0.12.zip](https://github.com/Tanguygab/TAB-Additions/files/15355531/TAB-Additions-2.0.12.zip)

**Comment by cosmunn** [comment]
The problem persists with this version. Same error.

```
[TAB v4.1.4] An error was thrown when executing task
java.lang.IllegalStateException: This player is not loaded yet. Try again later
	at TAB v4.1.4.jar//me.neznamy.tab.shared.platform.TabPlayer.ensureLoaded(TabPlayer.java:291)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.features.nametags.NameTag.showNameTag(NameTag.java:289)
	at TAB-Additions-2.0.12.jar//io.github.tanguygab.tabadditions.shared.features.ConditionalNametags.refresh(ConditionalNametags.java:54)
	at TAB-Additions-2.0.12.jar//io.github.tanguygab.tabadditions.shared.features.ConditionalNametags.refresh(ConditionalNametags.java:45)
	at TAB-Additions-2.0.12.jar//io.github.tanguygab.tabadditions.shared.features.ConditionalNametags.onJoin(ConditionalNametags.java:32)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:147)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:27)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:158)
	at TAB v4.1.4.jar//me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$1(CpuManager.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by cosmunn** [comment]
This one worked! Thank you very much!
