### ISSUE TITLE
TAB-Additions v1.6.2 is disabled on start

### ISSUE THREAD

**Issue by blockcrafter21** [Tanguygab/TAB-Additions#7]
I start my minecraft server : 
paper 1.18.1
TAB 3.0.1 
and it does not load .
When i execute /plugins TAB-Additions is highlighted red and executing an tab+ command for example makes an internal error
```
[14:37:40 ERROR]: null org.bukkit.command.CommandException: Cannot execute command 'tab+' in plugin TAB-Additions v1.6.2 -  
 plugin is disabled. at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]  
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?] at  
 org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-32] at  
 net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2201) ~[?:?] at  
 net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2012) ~[?:?] at  
 net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1993) ~[?:?] at  
 net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?] at  
 net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?] at  
 net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?] at  
 net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-32] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?] at  
 net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?] at  
 net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-32] at  
 net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-32] at  
 net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?] at  
 net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-32] at  
 net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-32] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?] at  
 net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.jar:git-Paper-32] at  
 net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-32] at  
 net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-32] at  
 java.lang.Thread.run(Thread.java:833) ~[?:?]  
```
Is thes a problem with TAB-Additions or with my server?

**Comment by Tanguygab** [comment]
send the entire log

**Comment by blockcrafter21** [comment]
i fixed it
